name: Setup Gradle Wrapper

on:
  workflow_dispatch: # Manual trigger only

jobs:
  setup-gradle:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Gradle
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.1.4-bin.zip
          unzip -q gradle-8.1.4-bin.zip
          export PATH=$PWD/gradle-8.1.4/bin:$PATH
          gradle --version

      - name: Debug: List directory structure before
        run: ls -R

      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.1.4 --distribution-type bin
          chmod +x ./gradlew
          ls -l ./gradlew gradlew.bat gradle/wrapper/

      - name: Debug: List directory structure after
        run: ls -R

      - name: Commit Gradle Wrapper files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add gradlew gradlew.bat gradle/wrapper/
          git commit -m "Add Gradle Wrapper files" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
